### ISSUE TITLE
Make Newsletter Permanent as a Blog

### ISSUE THREAD

**Issue by francopestilli** [brainlife/brainlife.hugo#12]
I have liked the content of the new-letters a lot. Unfortunately I fear the newsletter are read by only a few and I dislike the fact that they disappear in Trash Cans after a couple of days (if not seconds) after publishing.

I would like to suggest that we publish the newsletter as a Blog Post on the brainlife website. This will allow to provide a historical content for the work we have done.

**Comment by soichih** [comment]
Can we not link to this page? https://us12.campaign-archive.com/home/?u=0f52b0cd65a88d27aa83d8005&id=8d07cef694

**Comment by francopestilli** [comment]
Add a tab on the brainlife.io website so to link to the list of newsletters

**Comment by soichih** [comment]
I am going to add a link to the newsletter archive page from our website (landing page)

**Comment by soichih** [comment]
Added a link to previous newsletters

![Image](https://user-images.githubusercontent.com/923896/183979240-f0b08c13-5c20-42f2-b53f-497c8821e664.png)

**Comment by soichih** [comment]
@francopestilli please close this if you are happy.

**Comment by francopestilli** [comment]
It was closed already. I am happy.
