### ISSUE TITLE
Dan B: Update with NSF job listing and personal website

### ISSUE THREAD

**Issue by DanNBullock** [brainlife/brainlife.hugo#14]
https://github.com/brainlife/brainlife.hugo/blob/7e15c8a53506da2340811107ae9dae754eaad4ff/content/team.md?plain=1#L166-L167

The highlighted text can be augmented with this:

... Minnesota as a Postdoctoral Fellow. He now works as an AAAS Science and Technology Policy fellow at the National Science Foundation's Office of Advanced Cyberinfrastructure"

url: "https://dannbullock.github.io/"

**Comment by DanNBullock** [comment]
(Didn't want to do a pull request and clutter things up with a low-priority issue like this)

**Comment by francopestilli** [comment]
hi @DanNBullock the approach is to only follow graduates up to the first job after leaving the team. Otherwise we need to constantly update the text and that is not possible given how many of you we have.
